// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message.proto

package org.example.nettyDemo.Common.Proto;

public final class ProtobufOuter {
  private ProtobufOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code LetterType}
   */
  public enum LetterType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_MESSAGE = 0;</code>
     */
    USER_MESSAGE(0),
    /**
     * <code>NODE_MESSAGE = 1;</code>
     */
    NODE_MESSAGE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>USER_MESSAGE = 0;</code>
     */
    public static final int USER_MESSAGE_VALUE = 0;
    /**
     * <code>NODE_MESSAGE = 1;</code>
     */
    public static final int NODE_MESSAGE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LetterType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LetterType forNumber(int value) {
      switch (value) {
        case 0: return USER_MESSAGE;
        case 1: return NODE_MESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LetterType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LetterType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LetterType>() {
            public LetterType findValueByNumber(int number) {
              return LetterType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.example.nettyDemo.Common.Proto.ProtobufOuter.getDescriptor().getEnumTypes().get(0);
    }

    private static final LetterType[] VALUES = values();

    public static LetterType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LetterType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LetterType)
  }

  public interface UserMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 letter_id = 1;</code>
     * @return The letterId.
     */
    int getLetterId();

    /**
     * <code>.UserMessage.payload_type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.UserMessage.payload_type type = 2;</code>
     * @return The type.
     */
    org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type getType();

    /**
     * <pre>
     * other metadata
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code UserMessage}
   */
  public  static final class UserMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserMessage)
      UserMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserMessage.newBuilder() to construct.
    private UserMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserMessage() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              letterId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_UserMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_UserMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.class, org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code UserMessage.payload_type}
     */
    public enum payload_type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 每个枚举类型必须将其第一个类型映射为 0 作为默认值
       * </pre>
       *
       * <code>Text = 0;</code>
       */
      Text(0),
      /**
       * <code>Binary = 1;</code>
       */
      Binary(1),
      /**
       * <code>Integer = 2;</code>
       */
      Integer(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 每个枚举类型必须将其第一个类型映射为 0 作为默认值
       * </pre>
       *
       * <code>Text = 0;</code>
       */
      public static final int Text_VALUE = 0;
      /**
       * <code>Binary = 1;</code>
       */
      public static final int Binary_VALUE = 1;
      /**
       * <code>Integer = 2;</code>
       */
      public static final int Integer_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static payload_type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static payload_type forNumber(int value) {
        switch (value) {
          case 0: return Text;
          case 1: return Binary;
          case 2: return Integer;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<payload_type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          payload_type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<payload_type>() {
              public payload_type findValueByNumber(int number) {
                return payload_type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final payload_type[] VALUES = values();

      public static payload_type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private payload_type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:UserMessage.payload_type)
    }

    public static final int LETTER_ID_FIELD_NUMBER = 1;
    private int letterId_;
    /**
     * <code>int32 letter_id = 1;</code>
     * @return The letterId.
     */
    public int getLetterId() {
      return letterId_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.UserMessage.payload_type type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.UserMessage.payload_type type = 2;</code>
     * @return The type.
     */
    public org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type getType() {
      @SuppressWarnings("deprecation")
      org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type result = org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type.valueOf(type_);
      return result == null ? org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * other metadata
     * </pre>
     *
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (letterId_ != 0) {
        output.writeInt32(1, letterId_);
      }
      if (type_ != org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type.Text.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (letterId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, letterId_);
      }
      if (type_ != org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type.Text.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage)) {
        return super.equals(obj);
      }
      org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage other = (org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage) obj;

      if (getLetterId()
          != other.getLetterId()) return false;
      if (type_ != other.type_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LETTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLetterId();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserMessage)
        org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_UserMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_UserMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.class, org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.Builder.class);
      }

      // Construct using org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        letterId_ = 0;

        type_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_UserMessage_descriptor;
      }

      @java.lang.Override
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage getDefaultInstanceForType() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage build() {
        org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage buildPartial() {
        org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage result = new org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage(this);
        result.letterId_ = letterId_;
        result.type_ = type_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage) {
          return mergeFrom((org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage other) {
        if (other == org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.getDefaultInstance()) return this;
        if (other.getLetterId() != 0) {
          setLetterId(other.getLetterId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int letterId_ ;
      /**
       * <code>int32 letter_id = 1;</code>
       * @return The letterId.
       */
      public int getLetterId() {
        return letterId_;
      }
      /**
       * <code>int32 letter_id = 1;</code>
       * @param value The letterId to set.
       * @return This builder for chaining.
       */
      public Builder setLetterId(int value) {
        
        letterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 letter_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLetterId() {
        
        letterId_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.UserMessage.payload_type type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.UserMessage.payload_type type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.UserMessage.payload_type type = 2;</code>
       * @return The type.
       */
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type getType() {
        @SuppressWarnings("deprecation")
        org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type result = org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type.valueOf(type_);
        return result == null ? org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type.UNRECOGNIZED : result;
      }
      /**
       * <code>.UserMessage.payload_type type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage.payload_type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.UserMessage.payload_type type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * other metadata
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * other metadata
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * other metadata
       * </pre>
       *
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserMessage)
    }

    // @@protoc_insertion_point(class_scope:UserMessage)
    private static final org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage();
    }

    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserMessage>
        PARSER = new com.google.protobuf.AbstractParser<UserMessage>() {
      @java.lang.Override
      public UserMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.nettyDemo.Common.Proto.ProtobufOuter.UserMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 letter_id = 1;</code>
     * @return The letterId.
     */
    int getLetterId();

    /**
     * <code>.Response.mq_error error = 2;</code>
     * @return The enum numeric value on the wire for error.
     */
    int getErrorValue();
    /**
     * <code>.Response.mq_error error = 2;</code>
     * @return The error.
     */
    org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error getError();

    /**
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      error_ = 0;
      errorMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              letterId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              error_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.class, org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.Builder.class);
    }

    /**
     * Protobuf enum {@code Response.mq_error}
     */
    public enum mq_error
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      /**
       * <code>InternalServerError = 1;</code>
       */
      InternalServerError(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>InternalServerError = 1;</code>
       */
      public static final int InternalServerError_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static mq_error valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static mq_error forNumber(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return InternalServerError;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<mq_error>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          mq_error> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<mq_error>() {
              public mq_error findValueByNumber(int number) {
                return mq_error.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final mq_error[] VALUES = values();

      public static mq_error valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private mq_error(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Response.mq_error)
    }

    public static final int LETTER_ID_FIELD_NUMBER = 1;
    private int letterId_;
    /**
     * <code>int32 letter_id = 1;</code>
     * @return The letterId.
     */
    public int getLetterId() {
      return letterId_;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private int error_;
    /**
     * <code>.Response.mq_error error = 2;</code>
     * @return The enum numeric value on the wire for error.
     */
    public int getErrorValue() {
      return error_;
    }
    /**
     * <code>.Response.mq_error error = 2;</code>
     * @return The error.
     */
    public org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error getError() {
      @SuppressWarnings("deprecation")
      org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error result = org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error.valueOf(error_);
      return result == null ? org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error.UNRECOGNIZED : result;
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>string error_message = 3;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string error_message = 3;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (letterId_ != 0) {
        output.writeInt32(1, letterId_);
      }
      if (error_ != org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error.OK.getNumber()) {
        output.writeEnum(2, error_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (letterId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, letterId_);
      }
      if (error_ != org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, error_);
      }
      if (!getErrorMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.nettyDemo.Common.Proto.ProtobufOuter.Response)) {
        return super.equals(obj);
      }
      org.example.nettyDemo.Common.Proto.ProtobufOuter.Response other = (org.example.nettyDemo.Common.Proto.ProtobufOuter.Response) obj;

      if (getLetterId()
          != other.getLetterId()) return false;
      if (error_ != other.error_) return false;
      if (!getErrorMessage()
          .equals(other.getErrorMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LETTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLetterId();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + error_;
      hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.nettyDemo.Common.Proto.ProtobufOuter.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        org.example.nettyDemo.Common.Proto.ProtobufOuter.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.class, org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.Builder.class);
      }

      // Construct using org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        letterId_ = 0;

        error_ = 0;

        errorMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.Response getDefaultInstanceForType() {
        return org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.Response build() {
        org.example.nettyDemo.Common.Proto.ProtobufOuter.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.Response buildPartial() {
        org.example.nettyDemo.Common.Proto.ProtobufOuter.Response result = new org.example.nettyDemo.Common.Proto.ProtobufOuter.Response(this);
        result.letterId_ = letterId_;
        result.error_ = error_;
        result.errorMessage_ = errorMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.nettyDemo.Common.Proto.ProtobufOuter.Response) {
          return mergeFrom((org.example.nettyDemo.Common.Proto.ProtobufOuter.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.nettyDemo.Common.Proto.ProtobufOuter.Response other) {
        if (other == org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.getDefaultInstance()) return this;
        if (other.getLetterId() != 0) {
          setLetterId(other.getLetterId());
        }
        if (other.error_ != 0) {
          setErrorValue(other.getErrorValue());
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.nettyDemo.Common.Proto.ProtobufOuter.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.nettyDemo.Common.Proto.ProtobufOuter.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int letterId_ ;
      /**
       * <code>int32 letter_id = 1;</code>
       * @return The letterId.
       */
      public int getLetterId() {
        return letterId_;
      }
      /**
       * <code>int32 letter_id = 1;</code>
       * @param value The letterId to set.
       * @return This builder for chaining.
       */
      public Builder setLetterId(int value) {
        
        letterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 letter_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLetterId() {
        
        letterId_ = 0;
        onChanged();
        return this;
      }

      private int error_ = 0;
      /**
       * <code>.Response.mq_error error = 2;</code>
       * @return The enum numeric value on the wire for error.
       */
      public int getErrorValue() {
        return error_;
      }
      /**
       * <code>.Response.mq_error error = 2;</code>
       * @param value The enum numeric value on the wire for error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorValue(int value) {
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Response.mq_error error = 2;</code>
       * @return The error.
       */
      public org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error getError() {
        @SuppressWarnings("deprecation")
        org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error result = org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error.valueOf(error_);
        return result == null ? org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error.UNRECOGNIZED : result;
      }
      /**
       * <code>.Response.mq_error error = 2;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(org.example.nettyDemo.Common.Proto.ProtobufOuter.Response.mq_error value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        error_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Response.mq_error error = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        
        error_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>string error_message = 3;</code>
       * @return The errorMessage.
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error_message = 3;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error_message = 3;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error_message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string error_message = 3;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final org.example.nettyDemo.Common.Proto.ProtobufOuter.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.nettyDemo.Common.Proto.ProtobufOuter.Response();
    }

    public static org.example.nettyDemo.Common.Proto.ProtobufOuter.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.nettyDemo.Common.Proto.ProtobufOuter.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/message.proto\"\212\001\n\013UserMessage\022\021\n" +
      "\tletter_id\030\001 \001(\005\022\'\n\004type\030\002 \001(\0162\031.UserMes" +
      "sage.payload_type\022\014\n\004data\030\003 \001(\014\"1\n\014paylo" +
      "ad_type\022\010\n\004Text\020\000\022\n\n\006Binary\020\001\022\013\n\007Integer" +
      "\020\002\"\204\001\n\010Response\022\021\n\tletter_id\030\001 \001(\005\022!\n\005er" +
      "ror\030\002 \001(\0162\022.Response.mq_error\022\025\n\rerror_m" +
      "essage\030\003 \001(\t\"+\n\010mq_error\022\006\n\002OK\020\000\022\027\n\023Inte" +
      "rnalServerError\020\001*0\n\nLetterType\022\020\n\014USER_" +
      "MESSAGE\020\000\022\020\n\014NODE_MESSAGE\020\001B3\n\"org.examp" +
      "le.nettyDemo.Common.ProtoB\rProtobufOuter" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserMessage_descriptor,
        new java.lang.String[] { "LetterId", "Type", "Data", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "LetterId", "Error", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
